version: "3"

networks: 
    janenetwork:
        driver: bridge

services:

    php:
        container_name: php
        build: 
            context: ./containers/php
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www
        volumes: 
            - ./src:/var/www
        networks: 
            - janenetwork

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./storage/mysql:/var/lib/mysql
        networks: 
            - janenetwork
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment: 
            PMA_HOSTS: mysql
        #ports:
        #    - 8001:80
        networks: 
            - janenetwork
        depends_on: 
            - mysql

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./src:/var/www
            - ./containers/nginx:/etc/nginx/conf.d
            - ./storage/certs:/etc/nginx/certs
        networks: 
            - janenetwork
        depends_on:
            - php 
            - mysql
            - phpmyadmin
        #command: bash -c "/var/www/openssl.sh"