version: "3.7"

services:

    web:
        build: 
            context: ./
            dockerfile: ./containers/php/Dockerfile
        container_name: web
        restart: always
        working_dir: /var/www
        volumes: 
            - ./src:/var/www
        networks: 
            - janeserv

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./src:/var/www
            - ./containers/nginx:/etc/nginx/conf.d
        networks: 
            - janeserv

networks: 
    janeserv:
        driver: bridge